version: '3.7'
services:
  web:
    build: .
    command: gunicorn -b :5000 --access-logfile - --error-logfile - hardchat:app
    ports:
      - 5000:5000
    env_file:
      - .envfile
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev

volumes:
  postgres_data:
