"""add text field for status

Revision ID: 2924b87172cf
Revises: ae40f0b2193c
Create Date: 2020-05-14 23:07:51.984826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2924b87172cf'
down_revision = 'ae40f0b2193c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('text_status', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'text_status')
    # ### end Alembic commands ###
