"""add url for user

Revision ID: 81ed44311895
Revises: 2924b87172cf
Create Date: 2020-05-16 16:21:54.029393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81ed44311895'
down_revision = '2924b87172cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('url', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_users_url'), 'users', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_url'), table_name='users')
    op.drop_column('users', 'url')
    # ### end Alembic commands ###
