"""full data schema for 0.0.1

Revision ID: ae40f0b2193c
Revises: 7a39bcde1b13
Create Date: 2020-05-11 14:10:00.990734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae40f0b2193c'
down_revision = '7a39bcde1b13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chats_create_time'), 'chats', ['create_time'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('send_time', sa.DateTime(), nullable=True),
    sa.Column('message', sa.Text(length=512), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_send_time'), 'messages', ['send_time'], unique=False)
    op.create_table('talkers',
    sa.Column('user_role', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], ),
    sa.ForeignKeyConstraint(['uid'], ['users.id'], ),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_users_last_visit_time'), 'users', ['last_visit_time'], unique=False)
    op.create_index(op.f('ix_users_reg_time'), 'users', ['reg_time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_reg_time'), table_name='users')
    op.drop_index(op.f('ix_users_last_visit_time'), table_name='users')
    op.drop_table('talkers')
    op.drop_index(op.f('ix_messages_send_time'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_chats_create_time'), table_name='chats')
    op.drop_table('chats')
    # ### end Alembic commands ###
