name: Run python unit tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install python modules
      run: sudo apt install -y --no-install-recommends python3-venv python3-setuptools
    - name: Install pip packages
      run: |
        python3 -m venv .venv
        .venv/bin/pip install -r hard_chat_srv/requirements.txt
      env:
        PIPENV_VENV_IN_PROJECT: 1
    - name: Run unit tests
      run: .venv/bin/python hard_chat_srv/tests.py
